var BAIDU_API_KEY = 'I1GLzVm3vnEiZbQ9vsw3rmz7'
var BAIDU_SECRET_KEY = 'lC1fVWffyv8CzqnEICrsMCIW2imjOgfd'

var DEEPSEEK_API_KEY = 'sk-0e87f662cfb7461abc552d600a5de9c9'
var DEEPSEEK_BASE_URL = 'https://api.deepseek.com/v1'

module.exports = {
  BAIDU_API_KEY: BAIDU_API_KEY,
  BAIDU_SECRET_KEY: BAIDU_SECRET_KEY,
  DEEPSEEK_API_KEY: DEEPSEEK_API_KEY,
  DEEPSEEK_BASE_URL: DEEPSEEK_BASE_URL
}
